#유레카 서버 - 1
---
spring:
  profiles: server1
  application: 
    name: eureka-server1
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8889/eureka/,http://localhost:8899/eureka/
#eureka.instance.hostname=localhost
    registerWithEureka: true
    fetchRegistry: true
    
    
#유레카 서버 - 2
---
spring:
  profiles: server2
  application: 
    name: eureka-server2
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8889/eureka/,http://localhost:8899/eureka/
#eureka.instance.hostname=localhost
    registerWithEureka: true
    fetchRegistry: true
    
    
#주울
---
spring:
  profiles: dev

zuul: 
  routes: 
    search-apigateway.serviceId: eurekaclient
    search-apigateway.path: /api/**
eureka: 
  client: 
    serviceUrl.defaultZone: http://localhost:8889/eureka/,http://localhost
